title: Nam’s Dev Blog
description: 기록하는 개발자 남현서의 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://namhyunseo.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Nam Hyunseo
  email: your-email@example.com

minima:
  social_links:
    - { platform: github, user: namhyunseo }
