title: Namuteo
description: 개발과 그 외
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://namhyunseo.github.io"
lang: ko-KR
timezone: Asia/Seoul
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Nam Hyunseo

minima:
  header_pages:
    - index.md
    - deep-dive/index.html
    - til/index.html
    - honnamanmu/index.html
    - about.md
  social_links:
    - { platform: github, user: namhyunseo }

collections:
  til:
    output: true
    permalink: /til/:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-default.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "til"
    values:
      layout: til
